Object destructuring instead of defining property
OwenRay/Remote-MediaServer pull request #63
Opened 2019-12-12 22:25 UTC by dougmolineux

@OwenRay so this is a bit strange, but if I use the code provided here, I am able to play all my mp4 files. There are a few issues (such as thumbnails not showing up) but the actual videos play. 

When I don't use the object destructuring like this, then this line doesn't wait for the promise to resolve:
```
await FFProbe.getInfo(this.filePath).streams;
```
The `streams` variable remains undefined and we see the error that I described in my issue (https://github.com/OwenRay/Remote-MediaServer/issues/62). 

I feel like there is a deeper issue here that I don't quite understand, perhaps its due to my particular mp4's that I am having issues with, but this certainly seems to fix it. Please let me know if you have any thoughts or concerns about this.

Thank you!

2019-12-12 22:37 UTC, dougmolineux commented
Sorry to bore you with the details, but I think its because the `await` is referencing a property on the resolved object, I managed to reproduce this behavior:
```
function resolveAfter2Seconds(x) {
  return new Promise(resolve => {
    setTimeout(() => {
      resolve({ yep: x });
    }, 2000);
  });
}

async function f1() {
  var x = await resolveAfter2Seconds(10).yep;
  console.log(x); // undefined
}

f1();
```

2019-12-13 11:01 UTC, OwenRay commented
You're right, my stupid mistake.
It probably works usually because this info is also fetched when scanning and processing the files.
The files probably didn't fully finish processing or the processing got interrupted somehow.
Anyway, this should fix it indeed. ( thank you very much:) ) 
I have one little comment about this fix (will comment inline)

2019-12-13 11:04 UTC, OwenRay requested changes

2019-12-13 11:04 UTC, OwenRay commented on backend/modules/ffmpeg/MediaContentApiHandler.js
> +      ({ streams } = probe);
the ()'s aren't needed here.
so that makes: `{ streams } = probe;`
please fix that and I'll merge it

2019-12-13 11:05 UTC, OwenRay commented
btw, don't mind the build errors, it seems some binary has gone missing, that's an unrelated issue will look into that fixed right after the merge.

2019-12-13 15:25 UTC, dougmolineux commented
Oh no worries! I looked at this code for a long time, and started to question my understanding about async / await haha. Happens to the best of us :)

I thought exactly the same thing about the paranetheses, but for some reason when I omit them, I see an error like this:

![image](https://user-images.githubusercontent.com/880444/70810921-e220ab80-1d81-11ea-8b4d-fc6d8bd61c9c.png)

Additionally, when I run the code, I see this error crash on startup:
```
Unhandled promise rejection (rejection id: 1): SyntaxError: Unexpected token =
```
Apparently, we need to use something called "assignment without declaration syntax":

https://stackoverflow.com/questions/32138513/how-to-destructure-an-object-to-an-already-defined-variable

I believe that we could get rid of the parentheses if we weren't re-assigning a let variable. Please let me know if you know of a better way!

2019-12-13 19:49 UTC, OwenRay commented
My bad, you're 100% right. I'll merge it and will look into the build problems.

2019-12-13 19:50 UTC, merged

2019-12-16 18:37 UTC, dougmolineux commented
Wonderful, thank you!